title: Informatique pour tous en CPGE
author: Laurent Garcin
logo: logo.png

execute:
  execute_notebooks: cache
  allow_errors: true

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/lgarcin/CoursInformatique  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

exclude_patterns:
- env/*
- _scripts/*
- _databases/*

sphinx:
  extra_extensions:
    - sphinxcontrib.mermaid
    - sphinxcontrib.tikz
    - sphinx_exercise
  config:
    language: fr
    html_css_files:
      - "_static/mystyle.css"
    mathjax3_config:
      tex:
        macros:
          "dR": "\\mathbb{R}"
          "lb": "\\left[\\!\\left["
          "rb": "\\right]\\!\\right]"

parse:
  myst_enable_extensions:
    - deflist
    - dollarmath

html:
  favicon: logo.png